// flow-typed signature: 09cd765819efce302d7dc46ef1576a24
// flow-typed version: <<STUB>>/event-to-promise_v0.8.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'event-to-promise'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'event-to-promise' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'event-to-promise/dist/event-to-promise' {
  declare module.exports: any;
}

// Filename aliases
declare module 'event-to-promise/dist/event-to-promise.js' {
  declare module.exports: $Exports<'event-to-promise/dist/event-to-promise'>;
}
declare module 'event-to-promise/index' {
  declare module.exports: $Exports<'event-to-promise'>;
}
declare module 'event-to-promise/index.js' {
  declare module.exports: $Exports<'event-to-promise'>;
}
