// flow-typed signature: 0159749568234c605613cfe3c35d3a9f
// flow-typed version: <<STUB>>/prettier-package-json_v1.6.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prettier-package-json'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'prettier-package-json' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'prettier-package-json/src/defaultOptions' {
  declare module.exports: any;
}

declare module 'prettier-package-json/src/index' {
  declare module.exports: any;
}

declare module 'prettier-package-json/src/sort-contributors' {
  declare module.exports: any;
}

declare module 'prettier-package-json/src/sort-files' {
  declare module.exports: any;
}

declare module 'prettier-package-json/src/sort-scripts' {
  declare module.exports: any;
}

declare module 'prettier-package-json/tests/__helpers__/spawn' {
  declare module.exports: any;
}

declare module 'prettier-package-json/tests/command-line.test' {
  declare module.exports: any;
}

declare module 'prettier-package-json/tests/key-order.test' {
  declare module.exports: any;
}

declare module 'prettier-package-json/tests/script-order.test' {
  declare module.exports: any;
}

declare module 'prettier-package-json/tests/sort-contributors.test' {
  declare module.exports: any;
}

declare module 'prettier-package-json/tests/tab-width.test' {
  declare module.exports: any;
}

declare module 'prettier-package-json/tests/use-tabs.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'prettier-package-json/src/defaultOptions.js' {
  declare module.exports: $Exports<'prettier-package-json/src/defaultOptions'>;
}
declare module 'prettier-package-json/src/index.js' {
  declare module.exports: $Exports<'prettier-package-json/src/index'>;
}
declare module 'prettier-package-json/src/sort-contributors.js' {
  declare module.exports: $Exports<
    'prettier-package-json/src/sort-contributors'
  >;
}
declare module 'prettier-package-json/src/sort-files.js' {
  declare module.exports: $Exports<'prettier-package-json/src/sort-files'>;
}
declare module 'prettier-package-json/src/sort-scripts.js' {
  declare module.exports: $Exports<'prettier-package-json/src/sort-scripts'>;
}
declare module 'prettier-package-json/tests/__helpers__/spawn.js' {
  declare module.exports: $Exports<
    'prettier-package-json/tests/__helpers__/spawn'
  >;
}
declare module 'prettier-package-json/tests/command-line.test.js' {
  declare module.exports: $Exports<
    'prettier-package-json/tests/command-line.test'
  >;
}
declare module 'prettier-package-json/tests/key-order.test.js' {
  declare module.exports: $Exports<
    'prettier-package-json/tests/key-order.test'
  >;
}
declare module 'prettier-package-json/tests/script-order.test.js' {
  declare module.exports: $Exports<
    'prettier-package-json/tests/script-order.test'
  >;
}
declare module 'prettier-package-json/tests/sort-contributors.test.js' {
  declare module.exports: $Exports<
    'prettier-package-json/tests/sort-contributors.test'
  >;
}
declare module 'prettier-package-json/tests/tab-width.test.js' {
  declare module.exports: $Exports<
    'prettier-package-json/tests/tab-width.test'
  >;
}
declare module 'prettier-package-json/tests/use-tabs.test.js' {
  declare module.exports: $Exports<'prettier-package-json/tests/use-tabs.test'>;
}
