// flow-typed signature: 0d366af09a4f6768507b2efbd03f10c2
// flow-typed version: <<STUB>>/stream-mock_v1.2.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stream-mock'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stream-mock' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stream-mock/lib/commons/writable' {
  declare module.exports: any;
}

declare module 'stream-mock/lib/duplex-mock' {
  declare module.exports: any;
}

declare module 'stream-mock/lib/index' {
  declare module.exports: any;
}

declare module 'stream-mock/lib/readable-mock' {
  declare module.exports: any;
}

declare module 'stream-mock/lib/writable-mock' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stream-mock/lib/commons/writable.js' {
  declare module.exports: $Exports<'stream-mock/lib/commons/writable'>;
}
declare module 'stream-mock/lib/duplex-mock.js' {
  declare module.exports: $Exports<'stream-mock/lib/duplex-mock'>;
}
declare module 'stream-mock/lib/index.js' {
  declare module.exports: $Exports<'stream-mock/lib/index'>;
}
declare module 'stream-mock/lib/readable-mock.js' {
  declare module.exports: $Exports<'stream-mock/lib/readable-mock'>;
}
declare module 'stream-mock/lib/writable-mock.js' {
  declare module.exports: $Exports<'stream-mock/lib/writable-mock'>;
}
